### ISSUE TITLE
Add support for URLs

### ISSUE THREAD

**Issue by lluiscamino** [lluiscamino/fake-tweet#3]
If a URL is present on the tweet and, it should be displayed according to [Twitter cards docs](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started).

If the site has no `twitter:card` metatag, then the URL should be displayed as a regular link.

**Comment by lluiscamino** [comment]
Fixed with https://github.com/lluiscamino/fake-tweet/commit/23929fa03da4a5f3d5c90ffb72f4ac852078313e.

**Comment by dgca** [comment]
Hey @lluiscamino, just opened a PR here https://github.com/lluiscamino/fake-tweet/pull/18 that implements this. It's kinda rudimentary but I didn't wanna overcomplicate things.

**Comment by lluiscamino** [comment]
Thanks, closing this issue now!
